export type CertificationType = 
  | 'PCA' 
  | 'ACE' 
  | 'CSAE' 
  | 'Enterprise AI' 
  | 'Data Engineer' 
  | 'Network Specialist' 
  | 'Hybrid Architect';

export interface CaseStudy {
  id: string;
  number: number;
  title: string;
  subtitle: string;
  track: 'cloud-run' | 'agentic-ai' | 'security' | 'data-rag' | 'hybrid-dr';
  trackName: string;
  certifications: CertificationType[];
  challenge: string;
  solutionArchitecture: string;
  gcpServices: string[];
  metrics: string[];
  codeSnippet: string;
  codeSnippetTitle: string;
  examTakeaway: string;
}

export const CASE_STUDIES: CaseStudy[] = [
  // -------------------------------------------------------------------------
  // TRACK 1: ACCELERATE AI WITH CLOUD RUN (Case Studies 1-6)
  // -------------------------------------------------------------------------
  {
    id: 'cs-01-cold-start-elimination',
    number: 1,
    title: 'Cold-Start Elimination in GenAI Containers',
    subtitle: 'Achieving sub-800ms cold starts with CPU boost and distroless multi-stage builds',
    track: 'cloud-run',
    trackName: 'Cloud Run & GenAI Inference',
    certifications: ['ACE', 'PCA'],
    challenge: 'Heavy AI runtime libraries (TypeScript SDKs, Webpack chunks, client bundles) can trigger 5-10s container cold-start delays when scaling from zero instances upon sudden traffic spikes.',
    solutionArchitecture: 'Implement Docker multi-stage distroless base images to reduce container payload size from 1.2GB to 140MB. Pair with Google Cloud Run `--cpu-boost` flag which allocates 2x vCPU dynamically during the initialization phase before throttling to steady-state allocation.',
    gcpServices: ['Cloud Run', 'Artifact Registry', 'Cloud Build', 'Cloud Monitoring'],
    metrics: ['780ms p95 cold start', '88% image size reduction', '$0.00 idle cost'],
    codeSnippetTitle: 'Cloud Run Deployment with Startup CPU Boost',
    codeSnippet: `gcloud run deploy reflectai-app \\
  --image=us-central1-docker.pkg.dev/$PROJECT_ID/app/reflectai:latest \\
  --platform=managed \\
  --region=us-central1 \\
  --cpu-boost \\
  --min-instances=0 \\
  --max-instances=50 \\
  --concurrency=80 \\
  --memory=1Gi \\
  --update-labels=dev-tutorial=cloud-run-ai-challenge`,
    examTakeaway: 'For ACE & PCA exams: CPU boost doubles vCPU strictly during instance container startup without adding to steady-state memory billing, critical for meeting SLA on scale-to-zero GenAI workloads.'
  },
  {
    id: 'cs-02-gpu-sidecar-vllm',
    number: 2,
    title: 'GPU Sidecar & vLLM Microservices on Cloud Run',
    subtitle: 'Running high-throughput self-hosted open-weights models (Gemma 2) with Nvidia L4 GPUs',
    track: 'cloud-run',
    trackName: 'Cloud Run & GenAI Inference',
    certifications: ['Enterprise AI', 'PCA'],
    challenge: 'Enterprise data compliance mandates that sensitive employee thoughts remain on self-hosted model weights without egressing to public API endpoints, but dedicated GPU GKE clusters cost thousands monthly when idle.',
    solutionArchitecture: 'Package vLLM serving Gemma 2 9B into a GPU-enabled Cloud Run container with an attached Nvidia L4 GPU (24GB VRAM). Configure autoscaling scale-to-zero with a 15-minute idle scale-down delay, cutting monthly GPU expenditure by 74%.',
    gcpServices: ['Cloud Run GPUs', 'Artifact Registry', 'Cloud Storage', 'VPC Access Connector'],
    metrics: ['28 tokens/sec throughput', '74% cost reduction vs GKE', 'Scale-to-zero on idle'],
    codeSnippetTitle: 'Deploying Cloud Run with Nvidia L4 GPU Accelerator',
    codeSnippet: `gcloud beta run deploy gemma-inference-service \\
  --image=us-central1-docker.pkg.dev/$PROJECT_ID/models/vllm-gemma2:latest \\
  --gpu=1 \\
  --gpu-type=nvidia-l4 \\
  --memory=32Gi \\
  --cpu=8 \\
  --region=us-central1 \\
  --no-cpu-throttling \\
  --max-instances=5`,
    examTakeaway: 'PCA & AI Architect note: Cloud Run now supports hardware accelerators (Nvidia L4). Cloud Run with `--no-cpu-throttling` ensures background tensor memory processing finishes reliably between HTTP requests.'
  },
  {
    id: 'cs-03-http2-streaming-sse',
    number: 3,
    title: 'HTTP/2 Streaming & Server-Sent Events (SSE)',
    subtitle: 'Low-latency token-by-token thought generation without timeout dropouts',
    track: 'cloud-run',
    trackName: 'Cloud Run & GenAI Inference',
    certifications: ['PCA', 'ACE'],
    challenge: 'Long reflection responses from LLMs can take 15-30 seconds to fully generate. Standard HTTP/1.1 buffering causes proxies to time out or leaves users staring at blank loading spinners.',
    solutionArchitecture: 'Leverage Cloud Run native HTTP/2 end-to-end multiplexing paired with Next.js App Router edge streaming (\`ReadableStream\`). Tokens generated by Gemini are piped directly over Server-Sent Events (SSE), delivering First-Token-Time (TTFT) under 320ms.',
    gcpServices: ['Cloud Run', 'Gemini Flash API', 'Cloud Load Balancing'],
    metrics: ['320ms Time to First Token (TTFT)', '0 connection drops', 'HTTP/2 multiplexing'],
    codeSnippetTitle: 'Edge Streaming Route Handler in Next.js on Cloud Run',
    codeSnippet: `export const runtime = 'nodejs';

export async function POST(req: Request) {
  const { prompt } = await req.json();
  const stream = await geminiAi.models.generateContentStream({
    model: 'gemini-2.5-flash',
    contents: prompt,
  });

  const responseStream = new ReadableStream({
    async start(controller) {
      for await (const chunk of stream) {
        controller.enqueue(new TextEncoder().encode(chunk.text));
      }
      controller.close();
    }
  });

  return new Response(responseStream, {
    headers: { 'Content-Type': 'text/event-stream', 'Cache-Control': 'no-cache' }
  });
}`,
    examTakeaway: 'For PCA: Cloud Run supports request timeouts up to 60 minutes (default 5m). Enabling HTTP/2 end-to-end allows long-lived duplex streaming connections without requiring WebSocket servers.'
  },
  {
    id: 'cs-04-eventarc-async-multimodal',
    number: 4,
    title: 'Eventarc & Asynchronous Multimodal Ingestion',
    subtitle: 'Decoupling heavy voice and journal photo processing from user UI threads',
    track: 'cloud-run',
    trackName: 'Cloud Run & GenAI Inference',
    certifications: ['ACE', 'PCA'],
    challenge: 'Users uploading 5-minute audio voice memos or high-resolution handwritten journals cause HTTP timeouts and degrade interactive web app responsiveness if processed synchronously.',
    solutionArchitecture: 'Directly upload raw media to Google Cloud Storage via signed URLs. Google Cloud Storage emits an \`audit-log\` or \`storage.object.v1.finalized\` event through Eventarc, which triggers a background Cloud Run worker service to transcribe, analyze, and commit results to Firestore.',
    gcpServices: ['Eventarc', 'Cloud Storage', 'Cloud Run', 'Firestore', 'Gemini 2.5 Flash'],
    metrics: ['Sub-100ms UI upload acknowledgment', '10,000 parallel batch capacity', 'Zero dropped jobs'],
    codeSnippetTitle: 'Creating an Eventarc Trigger for Cloud Run Worker',
    codeSnippet: `gcloud eventarc triggers create storage-voice-processor \\
  --location=us-central1 \\
  --destination-run-service=media-analysis-worker \\
  --destination-run-region=us-central1 \\
  --event-filters="type=google.cloud.storage.object.v1.finalized" \\
  --event-filters="bucket=serene-ai-user-uploads" \\
  --service-account=eventarc-invoker@$PROJECT_ID.iam.gserviceaccount.com`,
    examTakeaway: 'For ACE & PCA: Eventarc converts Cloud Storage and 90+ GCP event sources into CloudEvents standards, routing them automatically to Cloud Run with automatic retries and dead-letter queues.'
  },
  {
    id: 'cs-05-concurrency-memory-tuning',
    number: 5,
    title: 'Micro-VM Concurrency & Memory Pressure Tuning',
    subtitle: 'Preventing container OOM crashes while optimizing instance packing density',
    track: 'cloud-run',
    trackName: 'Cloud Run & GenAI Inference',
    certifications: ['ACE', 'PCA'],
    challenge: 'Setting Cloud Run concurrency too high (e.g. 1000) causes out-of-memory crashes when multiple concurrent requests buffer large Gemini multimodal payloads; setting it too low (1) inflates infrastructure costs.',
    solutionArchitecture: 'Profile Node.js V8 heap overhead under peak loads. Tune Cloud Run concurrency to 80 requests per container with 1GiB RAM and configure \`--max-instances=50\`. Container autoscale calculations: Instances = \`ceil(Peak Concurrent Requests / 80)\`.',
    gcpServices: ['Cloud Run', 'Cloud Monitoring', 'Cloud Trace', 'Error Reporting'],
    metrics: ['0 OOM terminations in 1M calls', '80 req/container packing density', '42% lower compute bill'],
    codeSnippetTitle: 'Tuning Concurrency and Memory Quotas',
    codeSnippet: `gcloud run services update reflectai-app \\
  --concurrency=80 \\
  --memory=1Gi \\
  --cpu=1 \\
  --timeout=120s \\
  --max-instances=50 \\
  --region=us-central1`,
    examTakeaway: 'ACE Exam Rule: Cloud Run charges for resources strictly while requests are active when \`--no-cpu-throttling\` is off. Packing multiple requests via tuned concurrency dramatically lowers billable container-seconds.'
  },
  {
    id: 'cs-06-canary-prompt-deployment',
    number: 6,
    title: 'Blue/Green & Canary Traffic Splitting for Model Prompts',
    subtitle: 'Safely rolling out new system instructions and model versions with 0 downtime',
    track: 'cloud-run',
    trackName: 'Cloud Run & GenAI Inference',
    certifications: ['ACE', 'PCA'],
    challenge: 'Upgrading Gemini system instructions or swapping model tiers (e.g. 1.5 Flash to 2.5 Flash) can introduce unintended hallucinations or tone regression across active user reflection sessions.',
    solutionArchitecture: 'Deploy the new prompt engine as an unpromoted revision. Use Cloud Run native revision traffic tags to route 10% of production traffic to \`canary\` and 90% to \`stable\`. Monitor user sentiment and latency metrics in Cloud Operations before executing a 100% instantaneous cutover.',
    gcpServices: ['Cloud Run Revisions', 'Cloud Operations Suite', 'Artifact Registry'],
    metrics: ['0-downtime prompt migration', 'Instant 1-second rollback capability', '10/90 canary split'],
    codeSnippetTitle: 'Cloud Run 90/10 Canary Revision Traffic Split',
    codeSnippet: `# Deploy new revision without routing traffic
gcloud run deploy reflectai-app \\
  --image=us-central1-docker.pkg.dev/$PROJECT_ID/app/reflectai:v2 \\
  --no-traffic \\
  --tag=v2-canary

# Shift 10% traffic to canary and 90% to stable
gcloud run services update-traffic reflectai-app \\
  --to-tags=v2-canary=10,stable=90`,
    examTakeaway: 'ACE & PCA Classic: Cloud Run revisions are immutable. Traffic splitting happens at the Google Andromeda software-defined edge proxy, meaning 0 downtime and instantaneous microsecond rollback.'
  },

  // -------------------------------------------------------------------------
  // TRACK 2: AGENTIC AI & ENTERPRISE ORCHESTRATION (Case Studies 7-12)
  // -------------------------------------------------------------------------
  {
    id: 'cs-07-vertex-langgraph-cloudrun',
    number: 7,
    title: 'Vertex AI Reasoning Engine & LangGraph on Cloud Run',
    subtitle: 'Stateful multi-agent decision loops with Memorystore Redis checkpointing',
    track: 'agentic-ai',
    trackName: 'Agentic AI & Orchestration',
    certifications: ['Enterprise AI', 'PCA'],
    challenge: 'Autonomous AI agents need to maintain multi-step reasoning state across long-running tasks, but serverless Cloud Run containers are stateless and can terminate between conversational turns.',
    solutionArchitecture: 'Run LangGraph agent state machines inside Cloud Run with state checkpoints externalized to Google Cloud Memorystore (Redis). Each agent turn saves its graph state in Redis, allowing any autoscaled container instance to resume execution seamlessly.',
    gcpServices: ['Cloud Run', 'Memorystore for Redis', 'Serverless VPC Access', 'Vertex AI'],
    metrics: ['100% state durability across container restarts', '<4ms state retrieval latency'],
    codeSnippetTitle: 'LangGraph Redis Checkpointer Initialization',
    codeSnippet: `import { StateGraph } from '@langchain/langgraph';
import { RedisSaver } from '@langchain/langgraph-checkpoint-redis';

const redisSaver = new RedisSaver({
  host: process.env.REDIS_HOST, // Private IP from VPC Connector
  port: 6379,
});

const workflow = new StateGraph(AgentState)
  .addNode("triage", triageNode)
  .addNode("research", researchNode)
  .addEdge("triage", "research");

export const agentApp = workflow.compile({ checkpointer: redisSaver });`,
    examTakeaway: 'For Enterprise AI Architects: Serverless agents must be stateless at the compute tier while offloading memory to managed caching (Memorystore) connected via Serverless VPC Access.'
  },
  {
    id: 'cs-08-autonomous-tool-calling-maps',
    number: 8,
    title: 'Autonomous Tool Calling with Google Maps & Places API',
    subtitle: 'Deterministic JSON function calling for spatial travel & serenity agents',
    track: 'agentic-ai',
    trackName: 'Agentic AI & Orchestration',
    certifications: ['Enterprise AI', 'ACE'],
    challenge: 'LLMs naturally hallucinate locations, opening hours, and travel durations when asked to suggest physical sanctuaries for reflection and decompression.',
    solutionArchitecture: 'Equip Gemini 2.5 Flash with strict function-calling declarations (\`tools: [{ functionDeclarations: [...] }]\`). When a user asks for a quiet park, Gemini produces an exact JSON tool call. Cloud Run executes the Google Places API (New) and Routes API, grounding the output in real geographic coordinates.',
    gcpServices: ['Gemini API', 'Google Maps Platform', 'Places API (New)', 'Routes API'],
    metrics: ['0% location hallucination', 'Real-time transit duration accuracy', 'Type-safe JSON output'],
    codeSnippetTitle: 'Declaring Gemini Function Calling Tools in TypeScript',
    codeSnippet: `const searchPlacesTool = {
  name: 'searchQuietPlaces',
  description: 'Searches nearby quiet parks and botanical gardens using Google Places',
  parameters: {
    type: 'OBJECT',
    properties: {
      location: { type: 'STRING', description: 'City or coordinates' },
      radiusMeters: { type: 'NUMBER', description: 'Search radius' }
    },
    required: ['location']
  }
};

const chat = ai.chats.create({
  model: 'gemini-2.5-flash',
  config: { tools: [{ functionDeclarations: [searchPlacesTool] }] }
});`,
    examTakeaway: 'PCA & AI Specialist: Function Calling does not execute code inside the model; the model produces structured JSON function arguments that your secure application backend executes, preventing prompt injection.'
  },
  {
    id: 'cs-09-rag-vertex-search-grounding',
    number: 9,
    title: 'Grounding with Vertex AI Search & Enterprise Data',
    subtitle: 'Augmenting generative models with real-time enterprise document retrieval',
    track: 'agentic-ai',
    trackName: 'Agentic AI & Orchestration',
    certifications: ['Enterprise AI', 'PCA'],
    challenge: 'Generic LLMs lack context regarding proprietary corporate mindfulness manuals, internal wellness guidelines, and private organizational knowledge bases.',
    solutionArchitecture: 'Index enterprise policy PDFs in Google Cloud Storage and connect them to Vertex AI Search Data Stores. Enable Vertex AI Grounding in the Gemini API call so responses include verifiable source citations and page numbers with strict hallucination barriers.',
    gcpServices: ['Vertex AI Search', 'Cloud Storage', 'Gemini 2.5 Pro/Flash', 'Cloud IAM'],
    metrics: ['99.2% citation fidelity', 'Sub-second document retrieval', 'Automatic document chunking'],
    codeSnippetTitle: 'Grounding Gemini with Vertex AI Search Data Store',
    codeSnippet: `const response = await ai.models.generateContent({
  model: 'gemini-2.5-flash',
  contents: 'What are the enterprise wellness sabbatical policies?',
  config: {
    tools: [{
      retrieval: {
        vertexAiSearch: {
          datastore: 'projects/' + PROJECT_ID + '/locations/global/collections/default_collection/dataStores/' + DATASTORE_ID
        }
      }
    }]
  }
});`,
    examTakeaway: 'For PCA: Vertex AI Search provides managed RAG without requiring manual vector databases, chunking algorithms, or embedding pipelines, dramatically reducing operational maintenance.'
  },
  {
    id: 'cs-10-multi-agent-supervisor-hierarchy',
    number: 10,
    title: 'Multi-Agent Supervisor Hierarchy',
    subtitle: 'Orchestrating specialized Triage, Research, and Verification agents over internal gRPC',
    track: 'agentic-ai',
    trackName: 'Agentic AI & Orchestration',
    certifications: ['Enterprise AI', 'PCA'],
    challenge: 'A single prompt cannot simultaneously handle user emotion empathy, historical journal lookup, and fact-checking without suffering attention degradation across long context lengths.',
    solutionArchitecture: 'Deploy a multi-agent hierarchy: A "Supervisor Agent" routes prompts to specialized subagents ("Empathy Agent", "Memory Retrieval Agent", "Fact Verification Agent"). Services communicate internally over Cloud Run private service-to-service IAM authentication using gRPC.',
    gcpServices: ['Cloud Run Private Ingress', 'Cloud IAM', 'Vertex AI', 'Cloud Service Mesh'],
    metrics: ['3 specialized agents in parallel', '40% higher answer relevance', 'Full IAM mutual TLS encryption'],
    codeSnippetTitle: 'Service-to-Service Private Cloud Run Ingress',
    codeSnippet: `# Deploying worker agent accessible ONLY within VPC or authorized IAM callers
gcloud run deploy verification-agent \\
  --image=us-central1-docker.pkg.dev/$PROJECT_ID/agents/verifier:latest \\
  --ingress=internal \\
  --no-allow-unauthenticated \\
  --region=us-central1`,
    examTakeaway: 'PCA & Security: Using \`--ingress=internal\` restricts Cloud Run access exclusively to the internal VPC and authenticated GCP resources, completely blocking public internet attack vectors.'
  },
  {
    id: 'cs-11-human-in-the-loop-cloud-tasks',
    number: 11,
    title: 'Human-in-the-Loop (HITL) Guardrails with Cloud Tasks',
    subtitle: 'Pausing autonomous action execution pending user or clinical counselor authorization',
    track: 'agentic-ai',
    trackName: 'Agentic AI & Orchestration',
    certifications: ['PCA', 'Enterprise AI'],
    challenge: 'When an AI agent identifies severe distress or triggers high-impact external actions (like scheduling emergency counseling), autonomous execution must pause for explicit user confirmation.',
    solutionArchitecture: 'Dispatch the proposed action into Google Cloud Tasks with an execution delay or pending webhook state. The user receives a gentle confirmation dialog; upon approval, Cloud Tasks invokes the action handler. If rejected or timed out, the task self-purges.',
    gcpServices: ['Cloud Tasks', 'Cloud Run', 'Firestore', 'Firebase Cloud Messaging (FCM)'],
    metrics: ['100% human audit trail', 'Millisecond dispatch queuing', 'Configurable expiration timers'],
    codeSnippetTitle: 'Enqueuing a Human-in-the-Loop Approval Task',
    codeSnippet: `const client = new CloudTasksClient();
const parent = client.queuePath(PROJECT_ID, 'us-central1', 'agent-approvals');

const task = {
  httpRequest: {
    httpMethod: 'POST',
    url: 'https://reflectai-app-uc.a.run.app/api/agent/execute-approved',
    headers: { 'Content-Type': 'application/json' },
    body: Buffer.from(JSON.stringify({ actionId, userId, payload })).toString('base64'),
    oidcToken: { serviceAccountEmail: TASK_INVOKER_SA }
  },
  scheduleTime: { seconds: Math.floor(Date.now() / 1000) + 300 } // 5 min review window
};

await client.createTask({ parent, task });`,
    examTakeaway: 'For PCA: Cloud Tasks provides guaranteed at-least-once delivery, rate limiting, and scheduled execution with OIDC token service-account authentication.'
  },
  {
    id: 'cs-12-context-caching-finops',
    number: 12,
    title: 'Context Window Caching for Massive Codebases & Journals',
    subtitle: 'Slashing repeated token costs by 75% across frequent multi-turn conversations',
    track: 'agentic-ai',
    trackName: 'Agentic AI & Orchestration',
    certifications: ['Enterprise AI', 'PCA'],
    challenge: 'Passing 100,000+ tokens of personal journal history or large system instruction sets into Gemini on every conversational turn inflates API costs and increases latency.',
    solutionArchitecture: 'Utilize Gemini Context Caching API. Large static reference corpora (e.g. 50+ past user reflections or multi-megabyte company manuals) are cached in Gemini servers with a configurable Time-To-Live (TTL). Subsequent turns only transmit new deltas at a 75% cost discount.',
    gcpServices: ['Gemini API Context Caching', 'Cloud Run', 'Cloud Secret Manager'],
    metrics: ['75% token cost reduction', '60% faster response latency', 'Configurable 1-hour to 7-day TTL'],
    codeSnippetTitle: 'Creating a Reusable Gemini Context Cache',
    codeSnippet: `const cache = await ai.caches.create({
  model: 'gemini-2.5-flash',
  config: {
    ttl: '3600s', // 1 hour cached lifespan
    contents: [{ role: 'user', parts: [{ text: userHistoricalReflectionsCorpus }] }],
    systemInstruction: 'You are Serene AI, a compassionate sounding board.'
  }
});

// Query against cached context with minimal new token overhead
const response = await ai.models.generateContent({
  model: 'gemini-2.5-flash',
  contents: 'Based on my earlier reflections, what patterns emerged?',
  config: { cachedContent: cache.name }
});`,
    examTakeaway: 'Enterprise AI FinOps: Gemini Context Caching requires a minimum token threshold (32k+ tokens) and delivers 4x lower input pricing for cached tokens, crucial for multi-turn agentic applications.'
  },

  // -------------------------------------------------------------------------
  // TRACK 3: ENTERPRISE ZERO-TRUST, SECURITY & GOVERNANCE (Case Studies 13-18)
  // -------------------------------------------------------------------------
  {
    id: 'cs-13-vpc-service-controls-perimeter',
    number: 13,
    title: 'VPC Service Controls (VPC-SC) Perimeter',
    subtitle: 'Cryptographic data exfiltration barriers around Firestore, Cloud Storage & Vertex AI',
    track: 'security',
    trackName: 'Zero-Trust Security & Governance',
    certifications: ['PCA', 'CSAE'],
    challenge: 'A compromised developer credential or stolen service account key could allow malicious actors to dump entire Firestore journal databases or Vertex AI model artifacts to external storage buckets.',
    solutionArchitecture: 'Enclose sensitive GCP resources within a VPC Service Controls Security Perimeter. Even with valid IAM permissions, API requests originating from outside the authorized VPC network or perimeter boundary are blocked by Google’s edge proxies with an exfiltration denial.',
    gcpServices: ['VPC Service Controls', 'Access Context Manager', 'Firestore', 'Vertex AI', 'Cloud Storage'],
    metrics: ['0 unauthorized egress routes', 'Complete mitigation of insider threat data theft'],
    codeSnippetTitle: 'Defining an Access Policy Perimeter for VPC-SC',
    codeSnippet: `gcloud access-context-manager perimeters create serene_ai_perimeter \\
  --title="Serene AI Zero-Trust Vault" \\
  --resources="projects/$PROJECT_NUMBER" \\
  --restricted-services="firestore.googleapis.com,aiplatform.googleapis.com,storage.googleapis.com" \\
  --policy=$ACCESS_POLICY_ID`,
    examTakeaway: 'CSAE & PCA Essential: IAM controls "WHO" has access; VPC Service Controls controls "FROM WHERE" access is permitted, fundamentally preventing data exfiltration to unauthorized accounts.'
  },
  {
    id: 'cs-14-iap-context-aware-access',
    number: 14,
    title: 'Identity-Aware Proxy (IAP) & Context-Aware Access',
    subtitle: 'Zero-trust employee authentication without clunky enterprise VPN concentrators',
    track: 'security',
    trackName: 'Zero-Trust Security & Governance',
    certifications: ['PCA', 'CSAE'],
    challenge: 'Staff managing sensitive administrative consoles and clinical triage tools need access from remote locations without exposing admin URLs to the public internet or managing slow VPN tunnels.',
    solutionArchitecture: 'Front internal administrative routes with Google Cloud Identity-Aware Proxy (IAP) over a Cloud Load Balancer. IAP validates user Google Identity and device health context (OS version, corporate certificate, geolocation) before proxying requests to Cloud Run.',
    gcpServices: ['Identity-Aware Proxy (IAP)', 'Cloud Load Balancing', 'Access Context Manager', 'Cloud Run'],
    metrics: ['VPN-less zero-trust access', 'Device-health policy enforcement', 'Sub-second login latency'],
    codeSnippetTitle: 'Enabling IAP on Cloud Load Balancer Backend',
    codeSnippet: `gcloud compute backend-services update serene-admin-backend \\
  --iap=enabled,oauth2-client-id=$CLIENT_ID,oauth2-client-secret=$CLIENT_SECRET \\
  --global`,
    examTakeaway: 'For PCA & Security: IAP implements BeyondCorp zero-trust architecture by verifying user identity and context on every request at Google’s edge, removing the need for traditional network perimeters.'
  },
  {
    id: 'cs-15-secret-manager-zero-exposure',
    number: 15,
    title: 'Secret Manager Runtime Injection & Zero Token Leakage',
    subtitle: 'Eliminating hardcoded API keys through ephemeral container memory injection',
    track: 'security',
    trackName: 'Zero-Trust Security & Governance',
    certifications: ['ACE', 'PCA'],
    challenge: 'Accidentally committing \`.env.local\` files containing Gemini API keys or Firebase service account tokens to public GitHub repositories compromises company credentials in seconds.',
    solutionArchitecture: 'Store all sensitive tokens in Google Cloud Secret Manager. Grant the Cloud Run default service account the narrow role \`roles/secretmanager.secretAccessor\`. Inject secrets directly into environment variables at container launch via Cloud Run \`--set-secrets\`.',
    gcpServices: ['Cloud Secret Manager', 'Cloud IAM', 'Cloud Run'],
    metrics: ['0 secrets stored in source code', 'Automatic key rotation capability', 'AES-256 encrypted at rest'],
    codeSnippetTitle: 'Mounting Secret Manager Keys directly in Cloud Run',
    codeSnippet: `gcloud run services update reflectai-app \\
  --set-secrets=GEMINI_API_KEY=projects/$PROJECT_ID/secrets/gemini-api-key:latest,\\
GOOGLE_MAPS_API_KEY=projects/$PROJECT_ID/secrets/maps-api-key:latest \\
  --region=us-central1`,
    examTakeaway: 'ACE & PCA Core Practice: Never package secrets into container images or Dockerfiles. Use \`--set-secrets\` to inject values as memory-mapped environment variables or mounted volume files.'
  },
  {
    id: 'cs-16-workload-identity-federation',
    number: 16,
    title: 'Workload Identity Federation for Multi-Cloud & CI/CD',
    subtitle: 'Deploying from GitHub Actions and AWS without downloadable JSON service account keys',
    track: 'security',
    trackName: 'Zero-Trust Security & Governance',
    certifications: ['PCA', 'CSAE'],
    challenge: 'Long-lived JSON service account keys downloaded for CI/CD pipelines represent the #1 vulnerability for credential leaks and cloud account compromise.',
    solutionArchitecture: 'Establish Workload Identity Federation between GitHub Actions and Google Cloud IAM. GitHub uses short-lived OIDC tokens to authenticate with GCP STS (Security Token Service), trading them for temporary 1-hour credentials to deploy to Cloud Run.',
    gcpServices: ['Workload Identity Federation', 'Cloud IAM', 'Cloud Run', 'Security Token Service'],
    metrics: ['0 long-lived service account keys', '1-hour auto-expiring tokens', 'Cryptographic OIDC handshake'],
    codeSnippetTitle: 'Setting up Workload Identity Pool for GitHub Actions',
    codeSnippet: `gcloud iam workload-identity-pools create "github-pool" \\
  --location="global" --description="GitHub Actions Pool"

gcloud iam workload-identity-pools providers create-oidc "github-provider" \\
  --workload-identity-pool="github-pool" \\
  --issuer-uri="https://token.actions.githubusercontent.com" \\
  --attribute-mapping="google.subject=assertion.sub,attribute.repository=assertion.repository"`,
    examTakeaway: 'PCA & Security Mandatory: Google recommends Workload Identity Federation over downloadable service account keys for all external workloads (AWS, GitHub, Azure, Kubernetes).'
  },
  {
    id: 'cs-17-firestore-security-rules-abac',
    number: 17,
    title: 'Granular Firestore Security Rules with ABAC',
    subtitle: 'Cryptographic owner isolation enforcing zero cross-tenant journal leakage',
    track: 'security',
    trackName: 'Zero-Trust Security & Governance',
    certifications: ['CSAE', 'ACE'],
    challenge: 'A rogue client SDK query must never be able to read, update, or delete another user\'s private thoughts or reflection entries, even if client code is modified in the browser DevTools.',
    solutionArchitecture: 'Structure Firestore collections in a strict owner-partitioned hierarchy: \`/users/{userId}/entries/{entryId}\`. Enforce Attribute-Based Access Control (ABAC) in \`firestore.rules\` verifying that \`request.auth.uid == userId\` and validating payload timestamp formats.',
    gcpServices: ['Cloud Firestore', 'Firebase Authentication', 'Security Rules'],
    metrics: ['100% tenant isolation', 'Enforced at database core', 'Sub-millisecond rule evaluation'],
    codeSnippetTitle: 'Production Firestore Security Rules Architecture',
    codeSnippet: `rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /users/{userId}/entries/{entryId} {
      allow read, write: if request.auth != null && request.auth.uid == userId;
      allow create: if request.auth != null && request.auth.uid == userId
                    && request.resource.data.content is string
                    && request.resource.data.content.size() <= 20000;
    }
  }
}`,
    examTakeaway: 'For ACE & CSAE: Firestore Security Rules execute atomically on Google’s database servers. They cannot be bypassed by client-side tampering, securing multi-tenant applications effortlessly.'
  },
  {
    id: 'cs-18-cloud-armor-ddos-waf',
    number: 18,
    title: 'Cloud Armor DDoS Protection & Rate Limiting',
    subtitle: 'Protecting serverless AI endpoints from malicious scraping and credential stuffing',
    track: 'security',
    trackName: 'Zero-Trust Security & Governance',
    certifications: ['PCA', 'Network Specialist'],
    challenge: 'Malicious bots spamming the \`/api/gemini/reflection\` endpoint can trigger thousands of dollars in LLM inference costs and exhaust API quota limits within minutes.',
    solutionArchitecture: 'Place Google Cloud Armor Enterprise WAF in front of Cloud Run via a Global External Application Load Balancer. Implement rate-limiting rules restricting clients to 30 requests per IP per minute with adaptive pre-configured WAF rules against SQLi, XSS, and L7 floods.',
    gcpServices: ['Cloud Armor', 'Cloud Load Balancing', 'Cloud Run', 'Cloud Logging'],
    metrics: ['100,000 req/sec DDoS scrubbing', 'Layer 7 bot blocking', 'Automated IP throttling'],
    codeSnippetTitle: 'Cloud Armor Rate Limiting Security Policy',
    codeSnippet: `gcloud compute security-policies create serene-waf-policy --description="Rate limiting AI endpoints"

gcloud compute security-policies rules create 1000 \\
  --security-policy=serene-waf-policy \\
  --expression="true" \\
  --action="rate-based-ban" \\
  --rate-limit-threshold-count=30 \\
  --rate-limit-threshold-interval-sec=60 \\
  --ban-duration-sec=600 \\
  --conform-action=allow \\
  --exceed-action=deny-429`,
    examTakeaway: 'For PCA: Cloud Armor inspects traffic at Google’s global edge PoPs before traffic ever reaches Cloud Run, saving both compute billing and protecting container capacity.'
  },

  // -------------------------------------------------------------------------
  // TRACK 4: MODERN DATA PIPELINES, RAG & VECTOR STORAGE (Case Studies 19-23)
  // -------------------------------------------------------------------------
  {
    id: 'cs-19-alloydb-scann-vector-search',
    number: 19,
    title: 'AlloyDB Omni & pgvector with ScaNN Indexing',
    subtitle: 'Sub-5ms semantic similarity search across millions of reflective thoughts',
    track: 'data-rag',
    trackName: 'Data Mesh & Vector Stores',
    certifications: ['PCA', 'Data Engineer'],
    challenge: 'Searching through millions of historical user journal vectors using standard cosine distance in open-source PostgreSQL slows down dramatically as dataset size crosses 100,000 records.',
    solutionArchitecture: 'Deploy Google Cloud AlloyDB with the ScaNN (Scalable Nearest Neighbors) vector index extension. AlloyDB Omni provides Google-developed vector indexing algorithms offering 4x faster vector search and 3x higher throughput than standard PostgreSQL pgvector.',
    gcpServices: ['AlloyDB for PostgreSQL', 'ScaNN Vector Index', 'Cloud Run', 'Vertex AI Embeddings'],
    metrics: ['4.2ms p99 vector query latency', '4x faster than vanilla pgvector', 'Enterprise ACID compliance'],
    codeSnippetTitle: 'Creating a ScaNN Vector Index in AlloyDB',
    codeSnippet: `CREATE EXTENSION IF NOT EXISTS alloydb_scann;

CREATE INDEX user_journal_embedding_idx ON journal_entries 
USING scann (embedding cosine_distance) 
WITH (num_leaves = 1000, quantizer = 'sq8');

SELECT entry_id, content, 
       1 - (embedding <=> $query_embedding) AS similarity_score
FROM journal_entries
WHERE user_id = $user_id
ORDER BY embedding <=> $query_embedding
LIMIT 5;`,
    examTakeaway: 'For Data Engineers & PCA: AlloyDB is a fully managed PostgreSQL-compatible database with an intelligent columnar engine and Google-patented ScaNN vector indexing for high-scale RAG.'
  },
  {
    id: 'cs-20-bigquery-vector-search-embeddings',
    number: 20,
    title: 'BigQuery Vector Search & Gemini Embeddings in SQL',
    subtitle: 'Unified operational analytics and semantic search across billions of records',
    track: 'data-rag',
    trackName: 'Data Mesh & Vector Stores',
    certifications: ['PCA', 'Data Engineer'],
    challenge: 'Data teams managing AI pipelines typically need to export data into specialized vector databases (like Pinecone or Qdrant), introducing ETL pipeline failure points and synchronicity lag.',
    solutionArchitecture: 'Keep analytics and vector embeddings directly inside Google BigQuery. Use \`ML.GENERATE_EMBEDDING\` to vectorize user feedback and execute \`VECTOR_SEARCH\` directly in BigQuery SQL queries without moving data across external vendors.',
    gcpServices: ['BigQuery', 'BigQuery ML', 'Vertex AI Text-Embedding-004'],
    metrics: ['0 ETL data transfer pipelines', 'Petabyte-scale search scalability', 'Single-query SQL interface'],
    codeSnippetTitle: 'BigQuery SQL Vector Search Query',
    codeSnippet: `SELECT query.query_text, base.entry_id, base.content, distance
FROM VECTOR_SEARCH(
  TABLE \`serene_dw.journal_embeddings\`,
  'embedding',
  (SELECT ml_generate_embedding_result AS query_embedding, 'peaceful nature' AS query_text
   FROM ML.GENERATE_EMBEDDING(
     MODEL \`serene_dw.embedding_model\`,
     (SELECT 'peaceful nature' AS content)
   )),
  top_k => 5,
  distance_type => 'COSINE'
);`,
    examTakeaway: 'For Data Engineers: BigQuery Vector Search merges enterprise data warehousing with vector similarity search in a single SQL statement, eliminating external vector database silos.'
  },
  {
    id: 'cs-21-firestore-bigquery-realtime-cdc',
    number: 21,
    title: 'Firestore to BigQuery Real-Time CDC Pipeline',
    subtitle: 'Streaming operational document updates into enterprise data lakes with zero code',
    track: 'data-rag',
    trackName: 'Data Mesh & Vector Stores',
    certifications: ['Data Engineer', 'ACE'],
    challenge: 'Business intelligence analysts need to track user engagement, sentiment trends, and reflection frequencies without burdening the production Firestore NoSQL transactional database.',
    solutionArchitecture: 'Deploy the official Firebase "Stream Firestore to BigQuery" extension. Every document insert, update, or deletion in \`/users/{userId}/entries\` generates a change event automatically streamed to BigQuery tables partitioned by ingestion timestamp.',
    gcpServices: ['Cloud Firestore', 'BigQuery', 'Firebase Extensions', 'Cloud Functions'],
    metrics: ['Sub-second CDC streaming', '0 impact on operational Firestore read/write quotas'],
    codeSnippetTitle: 'BigQuery Querying Deduplicated Real-Time Journal Stream',
    codeSnippet: `SELECT 
  document_name,
  JSON_VALUE(data, '$.mood') AS user_mood,
  JSON_VALUE(data, '$.wordCount') AS entry_length,
  timestamp
FROM \`serene_dw.firestore_entries_raw_changelog\`
WHERE operation != 'DELETE'
QUALIFY ROW_NUMBER() OVER (PARTITION BY document_name ORDER BY timestamp DESC) = 1;`,
    examTakeaway: 'For ACE & Data Engineers: Change Data Capture (CDC) via Firebase Extensions streams operational NoSQL changes directly to BigQuery raw changelog tables without writing custom pub/sub extractors.'
  },
  {
    id: 'cs-22-document-ai-multimodal-pipeline',
    number: 22,
    title: 'Handwritten Journal Digitization with Document AI',
    subtitle: 'Extracting clean text and emotion cues from paper journals before LLM ingestion',
    track: 'data-rag',
    trackName: 'Data Mesh & Vector Stores',
    certifications: ['Enterprise AI', 'PCA'],
    challenge: 'Users photograph their physical paper journals. Direct image OCR with standard vision models fails on messy cursive handwriting and skewed camera angles.',
    solutionArchitecture: 'Route scanned journal images through Google Cloud Document AI Handwriting OCR processor. Document AI normalizes contrast, detects paragraph blocks, and outputs structured text and bounding boxes with confidence scores before feeding the text to Gemini.',
    gcpServices: ['Document AI', 'Cloud Storage', 'Cloud Run', 'Firestore'],
    metrics: ['96.4% cursive handwriting accuracy', 'Automatic image deskewing and cleanup'],
    codeSnippetTitle: 'Processing Scanned Journals via Document AI Node.js SDK',
    codeSnippet: `const { DocumentProcessorServiceClient } = require('@google-cloud/documentai').v1;
const client = new DocumentProcessorServiceClient();

const name = 'projects/' + PROJECT_ID + '/locations/us/processors/' + PROCESSOR_ID;
const [result] = await client.processDocument({
  name,
  rawDocument: { content: imageBuffer, mimeType: 'image/jpeg' }
});

const extractedText = result.document.text;`,
    examTakeaway: 'Enterprise AI: Document AI is purpose-built for enterprise document parsing, forms, and handwriting, delivering superior accuracy over generic OCR for document digitization.'
  },
  {
    id: 'cs-23-cloud-dlp-prompt-pii-redaction',
    number: 23,
    title: 'Cloud DLP Prompt Redaction & Sensitive Data Shield',
    subtitle: 'Automatically stripping PII and financial numbers before reaching LLM API endpoints',
    track: 'data-rag',
    trackName: 'Data Mesh & Vector Stores',
    certifications: ['CSAE', 'PCA'],
    challenge: 'Users frequently vent personal thoughts that contain sensitive personal data (Aadhaar cards, Social Security numbers, bank balances, or real full names) which violates enterprise compliance if stored in model training logs.',
    solutionArchitecture: 'Place Google Cloud Sensitive Data Protection (Cloud DLP) as an inline proxy before the Gemini SDK call. Cloud DLP inspects text against \`INFO_TYPE\` dictionaries, replacing names, phone numbers, and IDs with tokens (e.g. \`[REDACTED_PHONE]\`) in real-time.',
    gcpServices: ['Cloud DLP (Sensitive Data Protection)', 'Cloud Run', 'Gemini API'],
    metrics: ['100% PII redaction accuracy', '<12ms inspection latency', 'HIPAA & GDPR compliance'],
    codeSnippetTitle: 'Inline Cloud DLP De-identification Call',
    codeSnippet: `const { DlpServiceClient } = require('@google-cloud/dlp');
const dlp = new DlpServiceClient();

const [response] = await dlp.deidentifyContent({
  parent: 'projects/' + PROJECT_ID + '/locations/global',
  deidentifyConfig: {
    infoTypeTransformations: {
      transformations: [{
        primitiveTransformation: { replaceWithInfoTypeConfig: {} },
        infoTypes: [{ name: 'PHONE_NUMBER' }, { name: 'EMAIL_ADDRESS' }, { name: 'US_SOCIAL_SECURITY_NUMBER' }]
      }]
    }
  },
  item: { value: rawUserInput }
});

const sanitizedPrompt = response.item.value;`,
    examTakeaway: 'CSAE & Security: Cloud DLP (Sensitive Data Protection) provides automated inspection and tokenization/masking across text, images, and BigQuery tables to satisfy strict privacy regulations.'
  },

  // -------------------------------------------------------------------------
  // TRACK 5: HIGH AVAILABILITY, DR & HYBRID MULTI-CLOUD (Case Studies 24-28)
  // -------------------------------------------------------------------------
  {
    id: 'cs-24-multi-region-active-active',
    number: 24,
    title: 'Multi-Region Cloud Run Active-Active Load Balancing',
    subtitle: 'Zero-downtime global edge routing across us-central1 and europe-west1',
    track: 'hybrid-dr',
    trackName: 'Hybrid, DR & Multi-Cloud',
    certifications: ['PCA', 'Network Specialist'],
    challenge: 'A localized regional outage in Google Cloud \`us-central1\` could render the AI sanctuary unreachable, breaking enterprise SLAs for global corporate customers.',
    solutionArchitecture: 'Deploy identical Cloud Run containers to \`us-central1\` and \`europe-west1\`. Create a Global External Application Load Balancer with a single Anycast IP. Serverless Network Endpoint Groups (NEGs) route users to the geographically closest region; if one region fails, traffic auto-shifts in seconds.',
    gcpServices: ['Cloud Run (Multi-Region)', 'Global External Load Balancer', 'Serverless NEGs', 'Cloud Armor'],
    metrics: ['99.99% multi-region uptime SLA', '<50ms routing latency', 'Automatic failure rerouting'],
    codeSnippetTitle: 'Creating Serverless NEGs for Global Load Balancing',
    codeSnippet: `# Create Serverless NEG in US
gcloud compute network-endpoint-groups create neg-us-central1 \\
  --region=us-central1 --network-endpoint-type=serverless --cloud-run-service=reflectai-app

# Create Serverless NEG in EU
gcloud compute network-endpoint-groups create neg-europe-west1 \\
  --region=europe-west1 --network-endpoint-type=serverless --cloud-run-service=reflectai-app

# Add both to Global Backend Service
gcloud compute backend-services add-backend global-reflectai-backend \\
  --global --network-endpoint-group=neg-us-central1 --network-endpoint-group-region=us-central1
gcloud compute backend-services add-backend global-reflectai-backend \\
  --global --network-endpoint-group=neg-europe-west1 --network-endpoint-group-region=europe-west1`,
    examTakeaway: 'PCA Exam Classic: A single Global External Application Load Balancer with Serverless NEGs distributes requests across multiple Cloud Run regions over Google’s private global backbone.'
  },
  {
    id: 'cs-25-spanner-multi-region-replication',
    number: 25,
    title: 'Cloud Spanner Multi-Region Global Consistency',
    subtitle: '99.999% SLA relational storage with synchronized cross-continent read-write',
    track: 'hybrid-dr',
    trackName: 'Hybrid, DR & Multi-Cloud',
    certifications: ['PCA', 'Data Engineer'],
    challenge: 'Multi-tenant enterprise organizations require strict consistency and zero data loss for billing and subscription events across North America, Europe, and Asia without database replication lags.',
    solutionArchitecture: 'Deploy Google Cloud Spanner with a \`nam-eur-asia1\` multi-region instance configuration. TrueTime atomic clock synchronization guarantees external consistency (serializability) and five-nines (99.999%) availability with automatic zero-downtime failover.',
    gcpServices: ['Cloud Spanner', 'TrueTime API', 'Cloud IAM', 'Cloud KMS'],
    metrics: ['99.999% availability SLA', '0 replication lag (external consistency)', 'Multi-continent read scaling'],
    codeSnippetTitle: 'Provisioning a Multi-Region Cloud Spanner Instance',
    codeSnippet: `gcloud spanner instances create serene-enterprise-spanner \\
  --config=nam-eur-asia1 \\
  --description="Global Enterprise Spanner" \\
  --processing-units=1000`,
    examTakeaway: 'PCA Core Topic: Cloud Spanner is the only horizontally scalable relational database that provides TrueTime-backed external consistency with 99.999% SLA across continents.'
  },
  {
    id: 'cs-26-anthos-hybrid-cloud-connect',
    number: 26,
    title: 'Google Distributed Cloud (Anthos) & Hybrid Connect',
    subtitle: 'Running AI microservices on private bare-metal datacenters synchronized with GCP',
    track: 'hybrid-dr',
    trackName: 'Hybrid, DR & Multi-Cloud',
    certifications: ['Hybrid Architect', 'PCA'],
    challenge: 'Certain regulated defense and banking clients cannot place user journal data in public cloud regions due to strict data sovereignty mandates requiring on-premises server residency.',
    solutionArchitecture: 'Deploy Google Distributed Cloud (GDC Virtual / Anthos) on client on-premises VMware or bare-metal clusters. The management control plane is unified via Google Cloud Connect, allowing developers to deploy the exact same container images to on-prem and Cloud Run.',
    gcpServices: ['Google Distributed Cloud', 'Anthos Service Mesh', 'Cloud Interconnect', 'Artifact Registry'],
    metrics: ['100% on-premises data residency', 'Single Google Cloud Console management pane'],
    codeSnippetTitle: 'Registering On-Premises Cluster with GKE Hub',
    codeSnippet: `gcloud container fleet memberships register-admin-cluster on-prem-cluster-01 \\
  --kubeconfig=/etc/kubernetes/admin.conf \\
  --service-account-key-file=/etc/gcp/hub-service-account.json`,
    examTakeaway: 'Hybrid Architect & PCA: GDC (Anthos) delivers container consistency across on-premises, AWS, Azure, and Google Cloud, managed centrally via Fleet Management and Config Sync.'
  },
  {
    id: 'cs-27-disaster-recovery-rto-rpo',
    number: 27,
    title: 'Disaster Recovery (DR): Warm Standby vs Pilot Light',
    subtitle: 'Achieving RTO < 5 minutes and RPO = 0 across geographical disasters',
    track: 'hybrid-dr',
    trackName: 'Hybrid, DR & Multi-Cloud',
    certifications: ['PCA', 'CSAE'],
    challenge: 'In the event of a catastrophic regional failure, an enterprise cannot afford to lose a single submitted reflection entry (RPO=0) and must resume service in under 5 minutes (RTO < 5 min).',
    solutionArchitecture: 'Implement a "Warm Standby" architecture. Cloud Storage buckets are configured as Dual-Region (\`nam4\`: \`us-central1\` and \`us-east1\`) with Turbo Replication for 15-minute SLA. Cloud Run is pre-deployed to \`us-east1\` with \`--min-instances=0\` (Warm Standby costs zero compute dollars while idle).',
    gcpServices: ['Cloud Storage Dual-Region', 'Cloud DNS', 'Cloud Run', 'Cloud Monitoring'],
    metrics: ['RPO = 0 (zero data loss)', 'RTO < 3 minutes', '$0 compute standby overhead'],
    codeSnippetTitle: 'Configuring Turbo Replication on Dual-Region Buckets',
    codeSnippet: `gcloud storage buckets create gs://serene-ai-dual-vault \\
  --location=nam4 \\
  --uniform-bucket-level-access

gcloud storage buckets update gs://serene-ai-dual-vault \\
  --turbo-replication`,
    examTakeaway: 'PCA Exam Classic: Dual-Region storage with Turbo Replication guarantees 100% replication of new objects within 15 minutes, fulfilling RPO goals without running expensive redundant database clusters.'
  },
  {
    id: 'cs-28-finops-committed-use-discounts',
    number: 28,
    title: 'FinOps: Committed Use Discounts (CUDs) & Automated Shutdowns',
    subtitle: 'Optimizing cloud unit economics with 1-year commitments and Pub/Sub billing hooks',
    track: 'hybrid-dr',
    trackName: 'Hybrid, DR & Multi-Cloud',
    certifications: ['PCA', 'CSAE'],
    challenge: 'Startups and enterprise teams face budget overruns when unmonitored test workloads run unchecked over the weekend, leading to surprise monthly billing invoices.',
    solutionArchitecture: 'Apply 1-Year or 3-Year Flexible Committed Use Discounts (CUDs) covering baseline Cloud Run and database compute for a 52% cost reduction. Configure Cloud Billing budget threshold notifications to trigger a Pub/Sub topic which executes a Cloud Run function to dial down non-production instances to zero.',
    gcpServices: ['Cloud Billing', 'Committed Use Discounts', 'Pub/Sub', 'Cloud Run Functions'],
    metrics: ['52% discount on committed spend', '100% cap on unexpected budget overruns'],
    codeSnippetTitle: 'Automated Billing Threshold Cap Function',
    codeSnippet: `exports.stopBillingSpikes = async (pubsubEvent) => {
  const data = JSON.parse(Buffer.from(pubsubEvent.data, 'base64').toString());
  if (data.costAmount >= data.budgetAmount) {
    console.warn("BUDGET EXCEEDED! Disabling non-prod services...");
    // Scale non-critical Cloud Run services to max-instances=0
    await runClient.updateService({
      name: 'projects/serene-dev/locations/us-central1/services/staging-app',
      maxInstances: 0
    });
  }
};`,
    examTakeaway: 'For PCA & CSAE: CUDs offer up to 57% savings on predictable workloads. Budget alerts alone do not stop billing; you must wire Pub/Sub to an automated Cloud Function to disable services or disable billing programmatically.'
  }
];
